### ISSUE TITLE
add boolean operations on 3D solids

### ISSUE THREAD

**Issue by bergey** [diagrams/diagrams-lib#119]
We'd like to be able to combine 3D primitives with:
* union
* intersection
* difference

The good news is POVRay implements these primitives (though it calls union 'merge', and uses 'union' to refer to something else).  The bad news is it only supports them on primitive solids, not Paths or other interesting shapes we'll want down the road.  I haven't come up with a good forward-compatible design here.

OpenSCAD also supports these operations natively, of course.

**Comment by byorgey** [comment]
@bergey, isn't this done now?

**Comment by bergey** [comment]
Yes, I believe so.
