### ISSUE TITLE
add name field to ArrowOpts record

### ISSUE THREAD

**Issue by EdwardMorehouse** [diagrams/diagrams-lib#152]
Would it be possible to add a name field to the ArrowOpts record so that arrows created with connect and friends can be referenced for further processing.

In particular, I would like to be able to add labels to such arrows.

**Comment by byorgey** [comment]
Arrows get finalized too late for this to be of much use.  In particular, at the time you would be looking up a name you still really don't know exactly where the arrow will end up.  We really do want to support labelling arrows (and other things) but I think there are other ways to do that.  Closing this, feel free to reopen with compelling examples/use cases etc.
