### ISSUE TITLE
Add 3D-specific primitives, transformations, etc. to the standard library

### ISSUE THREAD

**Issue by fryguybob** [diagrams/diagrams-lib#16]
(Imported from <http://code.google.com/p/diagrams/issues/detail?id=31>. Original issue from byor...@gmail.com on May 16, 2011, 08:24:23 PM UTC)

Design and implement a ThreeD.* set of modules, parallel to the 2D-specific TwoD.* modules.  

  * 3D primitive shapes
  * 3D transformations
  * 3D alignment
  * etc.

This is technically separate from actually making a 3D backend although of course working on this ticket will probably not be much fun without a 3D backend.

**Comment by byorgey** [comment]
Of course there is always more to do, but we now have a lot of 3D stuff.  Closing this ticket in favor of more specific tickets detailing things yet to be done.
