### ISSUE TITLE
Move tests in Solve into a proper testing framework

### ISSUE THREAD

**Issue by Mathnerd314** [diagrams/diagrams-lib#189]
The blessed way to use QuickCheck seems to be to write the tests in a separate tests/ directory, and then run them using cabal's test-suite framework. We should probably do that instead of just letting them sit around in Solve.hs (where they do nothing).

**Comment by byorgey** [comment]
I think this ticket was from when Solve.hs was still in diagrams-lib; it has now been split out into diagrams-solve.
