### ISSUE TITLE
Factor out Diagrams.Solve into a package?

### ISSUE THREAD

**Issue by jtdaugherty** [diagrams/diagrams-lib#235]
I'd really *love* to use `Diagrams.Solve`, but I don't want to depend on `diagrams-lib` to do it. Would you be willing to factor this module out into a separate package? It looks like a relatively self-contained module so I imagine that wouldn't be onerous.

**Comment by byorgey** [comment]
It wouldn't be onerous to separate out the code into a package, but it could be onerous to support.  In particular the code in there is not based on any particular real knowledge of numerical computing.  It happens to work for us so far, but I am quite sure there are lurking bugs and I am not sure I would want to encourage others to use it.  On the other hand, maybe it would be a good way to get feedback and improve the code.

It continues to surprise me that there is no good package for numerical root-finding on Hackage.  There is http://hackage.haskell.org/package/roots but it seems abandoned, though it could certainly be revived.

Our of curiosity, what would you want to use it for?

**Comment by jtdaugherty** [comment]
I understand your concerns about support and correctness, although it's already public and people might already be using it, so moving it into another package would (at worst) just send the message that it's "more official" than it is now, but it'd be no more risky to use.  (And it could be shipped with a disclaimer.)

I looked at `roots`, but it doesn't even remotely have the API I want, and `Diagrams.Solve` had exactly that API so I was very happy to discover it. :)

As for what I want to do, I'd like to use it in my ray tracer project, https://github.com/jtdaugherty/tracy.  Right now I'm using `diagrams-lib` to get this module.

**Comment by byorgey** [comment]
OK, fair enough.  I'd be happy to split it out.  The other thing that might be nice to split out is the tridiagonal matrix solver in https://github.com/diagrams/diagrams-lib/blob/master/src/Diagrams/CubicSpline/Internal.hs.

**Comment by jtdaugherty** [comment]
Thank you!

**Comment by bergey** [comment]
I found myself copying `Solve.hs` into another project recently (err, also a raytracer, not nearly so far along).  I agree that splitting it out would be better, even with the caveats about robustness.

**Comment by byorgey** [comment]
OK, so now for the most difficult and important question: what should the
new package be called?

**Comment by jtdaugherty** [comment]
So long as it isn't some tortured thing that starts with "h", I don't care! :)

**Comment by byorgey** [comment]
OK, I think I will just call it `diagrams-solve`.  That makes it clear that the main purpose is just to collect solving routines needed for diagrams, and if it happens to be useful to others, so much the better.

**Comment by byorgey** [comment]
Uploaded `diagrams-solve-0.1` to Hackage.

**Comment by jtdaugherty** [comment]
Wonderful! Thank you! I've confirmed that my ray tracer works with the new package.
