### ISSUE TITLE
The semantics of `alignBL` and `snugBL` may not be what we want.

### ISSUE THREAD

**Issue by jeffreyrosenbluth** [diagrams/diagrams-lib#250]
`snugBL = snugB . snugL`, Unfortunately `snugB` and `snugL` do not commute so their
behavior is different, i.e `snugBL /= snugL. snugB`. This can lead to results that may not be 
intuitive (or useful) to users.

`snugBL`
![snugbl](https://cloud.githubusercontent.com/assets/1226936/7485467/31d4684e-f364-11e4-80d0-631fda1229c6.png)
`snugB . snugL`
![snuglb](https://cloud.githubusercontent.com/assets/1226936/7485482/6b717b96-f364-11e4-9948-5365f120ee3a.png)

At least `alignB` and `alignL` commute, but still it seems strange that `alignBL` puts the origin outside of
the hexagon. Whereas if we align in the (-1,-1) direction we end up on the hexagon.
`align ((-1) ^& (-1))`
![align11](https://cloud.githubusercontent.com/assets/1226936/7485438/e19e8530-f363-11e4-87ee-df07d4ef7fc6.png)
`alignBL`
![alignbl](https://cloud.githubusercontent.com/assets/1226936/7485459/13a2b5c4-f364-11e4-898c-c9617083d078.png)

One possible solution is to redefine both `alignBL` and `snugBL` as `align ((-1) ^& (-1))` ...

thoughts?

**Comment by cchalmers** [comment]
Yeah, the current `snugBL` doesn't make much sense. Maybe `snugSW` like you mentioned on irc could work but I'm still not sure how useful it would be.

I'm against changed `alignBL` and friends, it's very useful for getting this into a corner:

![SW vs BL](https://cloud.githubusercontent.com/assets/1354887/7488882/0a09b058-f3c8-11e4-950a-4cbd6c4c2266.png)

Maybe `alignSW` could be used for this too if you want it.

**Comment by bergey** [comment]
I'd like to keep the current semantics of `alignBL`.  I'm fine adding `alignSW`.  I have no opinion about the `snug` versions.

**Comment by jeffreyrosenbluth** [comment]
Ok, so we keep `alignBL` as is.
I'm starting to think we should simply deprecate `snugBL` and the like.

**Comment by cchalmers** [comment]
I'd be happy with that.

**Comment by byorgey** [comment]
Agree on keeping alignBL the way it is.  I would also be find deprecating
snugBL and the like.  I assume we already have a version of snug that can
take an arbitrary direction as a parameter?

**Comment by jeffreyrosenbluth** [comment]
yes we do have `snug` which takes an arbitrary direction as parameter.

**Comment by jeffreyrosenbluth** [comment]
To summarize:
  - we leave `alignBL` alone
  - we deprecated `snugBL`
