### ISSUE TITLE
Please add support for current versions of "fsnotify"

### ISSUE THREAD

**Issue by peti** [diagrams/diagrams-lib#259]
The current version of `fsnotify` is 0.2.1, but `diagrams-lib` still requires version 1.0:   http://packdeps.haskellers.com/feed?needle=diagrams-lib. It would be great if that limitation could be lifted.

**Comment by peti** [comment]
Will you release a new version to Hackage?

**Comment by byorgey** [comment]
I propose releasing this change, along with the new `composeAligned` function, as `diagrams-lib-1.3.1`.  @bergey, can you remind me what the new organization is with respect to the `release` and `master` branches, etc.?

**Comment by jeffreyrosenbluth** [comment]
sounds good to me

**Comment by bergey** [comment]
On 2015-08-07 at 21:23, Brent Yorgey <notifications@github.com> wrote:
> I propose releasing this change, along with the new `composeAligned`
> function, as `diagrams-lib-1.3.1`.  @bergey, can you remind me what
> the new organization is with respect to the `release` and `master`
> branches, etc.?

Sounds good.  If you're releasing something that isn't the current state
of `master`, please call the release branch `release`.  If all changes
on `master` are going into the release, it's easiest to release from
`master`, as we have always done.

I think `-lib`, `-contrib`, & `-rasterific` currently have `release`
branches, but there may be others.

This naming makes CI & other automation easier.

**Comment by byorgey** [comment]
Makes sense.  However, looking at it again, there's quite a bit more on `master` than just those things I mentioned (there's also bspline and csg stuff) so for now I will just release `1.3.0.3` with this change.

**Comment by byorgey** [comment]
Relased as `diagrams-lib-1.3.0.3`.
