### ISSUE TITLE
Broken offset joins with non-vertices in loops

### ISSUE THREAD

**Issue by robx** [diagrams/diagrams-lib#263]
I get broken offset paths when drawing a rectangle that has more points than just the four corners.

This happens with diagrams 1.3.0.3, it used to work with diagrams 1.2.

```
dia :: Diagram B
dia = (stroke p # lc blue)
    <> (stroke (offsetPath (-0.1 :: Double) p) # lc red)
    <> (stroke (offsetPath (0.1  :: Double) p) # lc green)
  where
    p :: Path V2 Double
    p = pathFromTrail . wrapTrail . glueLine . lineFromVertices . map p2 $
--          [(0,0), (2,0), (2,1), (2,2), (0,2), (0,0)] -- broken
            [(0,0), (2,0), (2,2), (0,2), (0,0)] -- fine
```

![broken](https://cloud.githubusercontent.com/assets/132113/10166838/34853cfa-66c6-11e5-85d5-8fa37ecb982d.png)
![fine](https://cloud.githubusercontent.com/assets/132113/10166871/5611af66-66c6-11e5-9c07-bd5800eb59c0.png)

**Comment by byorgey** [comment]
@fryguybob can you take a look?

**Comment by fryguybob** [comment]
My guess is that the straight joint leads to a zero length segment that gets removed, but throws off the rest of the stitching together.  I'll take a look soon.

**Comment by robx** [comment]
Just wondering, is there any chance of a bugfix release which includes this fix?

**Comment by bergey** [comment]
@robx If you can backport the change to the `release` branch, test that it works, and make a PR, I will push it to Hackage.
