### ISSUE TITLE
Transient out-of-memory errors in test suite

### ISSUE THREAD

**Issue by byorgey** [diagrams/diagrams-lib#277]
For example, see https://travis-ci.org/diagrams/diagrams-lib/jobs/135723936 .

A bit of previous discussion here: https://github.com/diagrams/diagrams-lib/pull/276#issuecomment-224276548

**Comment by byorgey** [comment]
The failing test (at least in the above example, not sure if it sometimes fails at other points) is here: https://github.com/diagrams/diagrams-lib/blob/master/test/Diagrams/Test/TwoD.hs#L16 .  Since the `arc` function can (intentionally) generate arcs which wrap around multiple times, if we randomly generate a very large `Angle` it will generate an arc path with many segments.

**Comment by bergey** [comment]
Oh, that makes sense.  I had forgotten the wrap-around.

@dashhalpern is planning to look into fixing this.

**Comment by byorgey** [comment]
Great!

**Comment by byorgey** [comment]
@bergey , do you know if @dashhalpern is still planning to work on this?  I'd love to get it resolved before the 1.4 release.

**Comment by byorgey** [comment]
No worries, I ended up doing it myself.
