### ISSUE TITLE
Could not deduce (Num n) arising from a use of `output'

### ISSUE THREAD

**Issue by nomeata** [diagrams/diagrams-lib#280]
On Debian, I observe this build error:
```
[60 of 72] Compiling Diagrams.Attributes ( src/Diagrams/Attributes.hs, dist-ghc/build/Diagrams/Attributes.o )

src/Diagrams/Attributes.hs:170:12:
    Could not deduce (Num n) arising from a use of `output'
    from the context (N a ~ n, HasStyle a, Typeable n)
      bound by the type signature for
                 lwO :: (N a ~ n, HasStyle a, Typeable n) => n -> a -> a
      at src/Diagrams/Attributes.hs:169:8-55
    Possible fix:
      add (Num n) to the context of
        the type signature for
          lwO :: (N a ~ n, HasStyle a, Typeable n) => n -> a -> a
    In the second argument of `(.)', namely `output'
    In the expression: lw . output
    In an equation for `lwO': lwO = lw . output

src/Diagrams/Attributes.hs:223:29:
    Could not deduce (Num n) arising from a use of `output'
    from the context (N a ~ n, HasStyle a, Typeable n)
      bound by the type signature for
                 dashingO :: (N a ~ n, HasStyle a, Typeable n) => [n] -> n -> a -> a
      at src/Diagrams/Attributes.hs:222:13-67
    Possible fix:
      add (Num n) to the context of
        the type signature for
          dashingO :: (N a ~ n, HasStyle a, Typeable n) => [n] -> n -> a -> a
    In the first argument of `map', namely `output'
    In the first argument of `dashing', namely `(map output w)'
    In the expression: dashing (map output w) (output v)
/usr/share/cdbs/1/class/hlibrary.mk:147: recipe for target 'build-ghc-stamp' failed
```
https://buildd.debian.org/status/fetch.php?pkg=haskell-diagrams-lib&arch=amd64&ver=1.3.1.3-1&stamp=1468364701

Any ideas?

**Comment by cchalmers** [comment]
The `Num` constraint on `output` was removed in `diagrams-core-1.3.0.8` and the `Num` constraint from `lwO` was removed from `diagrams-lib-1.3.1.3`. So if you try to build with an earlier version of `-core` you'll get this error.

So I guess we need to make `-lib` depending of on the latest `diagrams-core`.  I'm not sure if these fixes this should have been a bigger version bump with respect to our version policy?

**Comment by nomeata** [comment]
Thanks, I will update `-core` accordingly in Debian.

> So I guess we need to make -lib depending of on the latest diagrams-core.

I agree.

>  I'm not sure if these fixes this should have been a bigger version bump with respect to our version policy?

Looks like the removal of a constraint is forward-compatible, but not backward-compatible, and should require  a bump of the third number in `-core`, and `-lib` should depend on >= i.j.k, where k is the oldest tested version.

**Comment by byorgey** [comment]
Edited `diagrams-lib.cabal` on Hackage to change the lower bound on `diagrams-core` to 1.3.0.8.  Though I agree technically we should bump the third number of `-core` I am not terribly inclined to do that right now, especially since we will soon be releasing diagrams 1.4.  I could be talked into it thought.
