### ISSUE TITLE
Intersection parameter

### ISSUE THREAD

**Issue by mpwp** [diagrams/diagrams-lib#283]
Hello!

I'm trying to generate gear profile with diagrams and I can't find a way to correct a "glitch".
![g3492](https://cloud.githubusercontent.com/assets/12151846/18782325/4018d76c-8186-11e6-8f2e-132ffffc6e59.png)
In input, I have the gear cutter (in orange) which is deformed to obtain the gear profile (in blue).
As you can see, I have an undercut on the tooth head (due to the generation process, diagrams works pretty well here!).
![g4300](https://cloud.githubusercontent.com/assets/12151846/18782448/d57287fe-8186-11e6-9d97-09d74faaecde.png)
In order to cut that, I can have the point of intersection with any `intersectPoints*` in `Diagrams.TwoD`.
But I can't find a way to find the parameters on each paths to call `splitAtParam` from `Diagrams.Parametric`.

Is it possible to do what I'm trying? Otherwise, can I have some clues to implement this?
Or maybe do you have some alternatives?

Thanks!

**Comment by cchalmers** [comment]
Unfortunately I haven't finished the intersection code so there's not yet a direct way to get what you want. I think [`segmentSegment`](http://hackage.haskell.org/package/diagrams-lib-1.3.1.4/docs/Diagrams-TwoD-Segment.html#v:segmentSegment) from [`Diagrams.TwoD.Segment`](http://hackage.haskell.org/package/diagrams-lib-1.3.1.4/docs/Diagrams-TwoD-Segment.html) will help. You should be able to do it by splitting the trail into segments using [`fixTrail`](http://hackage.haskell.org/package/diagrams-lib-1.3.1.4/docs/Diagrams-Trail.html#v:fixTrail), use `segmentSegment` on the intersecting segments and use the result to calculate the intersection parameters of the original trail (this is probably the trickiest bit).

Hope this helps, let me know if you get stuck.

**Comment by mpwp** [comment]
Yep, it helps a lot. I missed `fixTrail` a dozen of times...
I may have a solution but struggling to *reverse* `fixTrail`.

I won't show the code now, cause it's an ugly boilerplate but the idea is:
As the intersection is always between the first two `Located (Trail V2 n)`, it maps fixTrail on them.
It takes all the segments (of the first) until the intersection, where it splits and drops the rest.
On the second, it drops every segments until the intersection and takes the rest.
Then I need to go back from the wonderful world of segments to something *renderable* and I miss something else.

I'm going to try something like:
`test :: [FixedSegment v n] -> Trail v n`
`test = trailFromSegments . map (unLoc . fromFixedSeg)`
But I've no idea how to not lose the *location*.

**Comment by byorgey** [comment]
The location of the resulting `Trail` should be the location of the first `FixedSegment`.  It's not particularly pretty, but something like this should work:

```
convert :: [FixedSegment v n] -> Located (Trail v n)
convert = mapLoc trailFromSegments . takeLoc . map fromFixedSeg
  where
    takeLoc xxs@(x:xs) = map unLoc xxs `at` loc x

**Comment by mpwp** [comment]
It works! Thank you so much!

In case anyone as a similar problem, here the fix:
(please, note that this solution may not work for any problem)

```haskell
correctedProfile :: GearShape -> Double -> [Located (Trail V2 Double)]
correctedProfile gs z = a' : b' : cs
  where
    (a:b:cs) = cutted gs z  -- cutted is the function generating the raw gear profile

    a' = convert $ startSegments (fixTrail a) (fixTrail b)
    b' = convert $ endSegments (fixTrail b) (fixTrail a)

    intersections v vs = concatMap (segmentSegment 0.01 v) vs

    startSegments (x:xs) ys = if null (intersections x ys)
      then x : startSegments xs ys
      else [fst . splitAtParam x . fst3 . head $ intersections x ys]

    endSegments (x:xs) ys = if null (intersections x ys)
      then endSegments xs ys
      else (snd . splitAtParam x . fst3 . head $ intersections x ys) : xs
```

As you might guess, in a near future, there will be a small gear profile generator in haskell using the diagrams library. So keep up the nice and good work! :)

**Comment by byorgey** [comment]
Great!  Do you think there are parts of this that could be extracted into some general functions we could add to the library?

**Comment by mpwp** [comment]
Maybe, I don't know yet.

But not like that. As you can see, it just checks for an intersection between the first two trails... and there is missing pattern matching for `startSegments` and `endSegments` functions.

I need to do some refactoring, so I will come back (here) with proposals.

**Comment by byorgey** [comment]
OK.  At the very least I think we should make that `convert` function available (with appropriate caveats).  See #284.
