### ISSUE TITLE
diagrams-lib-1.4.0.1 versus 32 bit platforms

### ISSUE THREAD

**Issue by peti** [diagrams/diagrams-lib#289]
I get the following warning on i686 platforms, which looks kinda serious:

~~~
src/Diagrams/Backend/CmdLine.hs:612:21: warning: [-Woverflowed-literals]
    Literal 5000000000000 is out of the Int range -2147483648..2147483647
~~~

**Comment by byorgey** [comment]
Thanks!  It turns out that number just so happens to overflow to a *positive* 32-bit int, and it was used as an argument to `forever . threadDelay`, so in fact I don't think this should have caused any erroneous behavior.  But on principle I certainly agree this is bad!
