### ISSUE TITLE
API request: loadImageEmb should have a non-IO counterpart

### ISSUE THREAD

**Issue by dfordivam** [diagrams/diagrams-lib#291]
Currently `loadImageEmb` needs to do IO and read from file.
```
loadImageEmb :: Num n => FilePath -> IO (Either String (DImage n Embedded)) 
```
This is a request to provide a pure version if the `ByteString` is provided
```
loadImageEmbBS :: Num n => ByteString -> Either String (DImage n Embedded)
```
PS: I tried to do this, but it seems the diagrams-lib does not have a dependence on `bytestring` package. Not sure whether it is possible to do this in the lib itself.

**Comment by byorgey** [comment]
Good idea.  Actually, `diagrams-lib` already does depend on `bytestring` --- transitively, via `lens`.  So `bytestring` would need to be added to the list of dependencies in `diagrams-lib.cabal`, but this does not change the set of packages that users would need to install anyway.

**Comment by dfordivam** [comment]
Great. So I will send a PR with this change...

**Comment by byorgey** [comment]
Great, thanks!  Indeed, `bytestring` is already a dependency for multiple reasons.
