### ISSUE TITLE
dirBetween is the 'wrong way round'

### ISSUE THREAD

**Issue by mpilgrem** [diagrams/diagrams-lib#303]
`dirBetween` is implemented as:
~~~~
-- | @dirBetween p q@ returns the directions from @p@ to @q@
dirBetween :: (Additive v, Num n) => Point v n -> Point v n -> Direction v n
dirBetween p q = dir $ p .-. q
~~~~
However, `p` minus `q` is the direction from `q` to `p` (not from `p` to `q`). The haddock documentation and the logic are inconsistent.

The user manual is similarly incorrect, [here](https://archives.haskell.org/projects.haskell.org/diagrams/doc/manual.html#vectors-and-points) (last but one sentence).

**Comment by byorgey** [comment]
Oh, good catch, thanks!
