### ISSUE TITLE
Grid layout module

### ISSUE THREAD

**Issue by fryguybob** [diagrams/diagrams-lib#33]
(Imported from <http://code.google.com/p/diagrams/issues/detail?id=70>. Original issue from byor...@gmail.com on March  9, 2012, 10:42:48 PM UTC)

There should be a diagrams-lib module with tools for laying out items in a grid/lattice. Not sure exactly what the API should look like, but ideally it would have features like:

  * ability to specify arbitrary basis vectors in order to get non-axis aligned grids, or even &quot;parallelogram-shaped&quot; grids
  * (optional) automatic calculation of grid spacing based on max size of items in the grid
  * it can probably be made vector-space-agnostic, e.g. there's no particular reason we can't have 3D grids

**Comment by byorgey** [comment]
We now have several grid modules in `-contrib`.
