### ISSUE TITLE
Can Diagrams.Uitl.(#) be deprecated in favor of Data.Function.(&) ?

### ISSUE THREAD

**Issue by wizzup** [diagrams/diagrams-lib#332]
[Data.Function.(&)](https://hackage.haskell.org/package/base/docs/Data-Function.html#v:-38-) is in  `base` since version 4.8.0.0 (ghc 7.10.1, Apr 2015)

```
(&) :: a -> (a -> b) -> b
x & f = f x
```

Despite the fact that [(#)](https://github.com/diagrams/diagrams-lib/blame/master/src/Diagrams/Util.hs#L89) was came years before, I wonder if the later could be deprecated in favor of the former to maintain consistency among new code in the future?

**Comment by bacchanalia** [comment]
A reason to keep (#) is that (#) is infixl 8, while (&) is infixl 1. This is particularly useful for Diagrams because (#) binds tighter than other common diagram operations like (<>), (|||), and (===), which are infix* 6.

**Comment by byorgey** [comment]
Yes, it's a good suggestion in principle, but the difference in precedence is exactly the reason that we don't do this.
