### ISSUE TITLE
Bitmap support

### ISSUE THREAD

**Issue by fryguybob** [diagrams/diagrams-lib#34]
(Imported from <http://code.google.com/p/diagrams/issues/detail?id=75>. Original issue from byor...@gmail.com on March 14, 2012, 11:51:41 PM UTC)

Sometimes users want to render some sort of grid of a large number of pixels as part of a diagram; creating a grid of squares (e.g. using hcat and vcat) is not a very efficient way to this, for those backends which can support bitmaps more directly.  The idea would be to add some sort of new &quot;bitmap&quot; primitive to diagrams-lib, which is stored in a memory-efficient way and can be rendered more directly by some backends.  Perhaps a fallback method could also be provided to convert a bitmap into a grid of squares, for use by those backends which cannot directly support bitmaps.

**Comment by byorgey** [comment]
This is now done, with the `Image` type.
