### ISSUE TITLE
New release on Hackage to allow GHC 8.8.1

### ISSUE THREAD

**Issue by wismill** [diagrams/diagrams-lib#344]
Hello, could you upload a new release on Hackage to be able to compile the diagrams-* libraries with GHC 8.8.1?
Thanks for the great work!

**Comment by byorgey** [comment]
Thanks for the nudge, working on it!

**Comment by byorgey** [comment]
`diagrams-lib-1.4.3` has now been released to Hackage.  Note that there are still other packages in the diagrams ecosystem that need to be updated, but I'm working on those too!

**Comment by wismill** [comment]
Thanks!
