### ISSUE TITLE
Is diagrams-lib master supposed to work only with GHC-7.10.3

### ISSUE THREAD

**Issue by phadej** [diagrams/diagrams-lib#346]
Because 

```
build-depends: base >= 4.7
```

suggest that GHC-7.8.4 would be supported meta-data wise?

EDIT: it's actually `base >= 4.6` atm, suggesting that even GHC-7.6. should potentially work.

**Comment by byorgey** [comment]
Yes, we're dropping support for GHC 7.8.  I always forget to update lower bounds.

**Comment by byorgey** [comment]
This was addressed by https://github.com/diagrams/diagrams-lib/commit/964843b85549c4d4c264bee147c842ceb59b1575 .
