### ISSUE TITLE
diagrams-lib-1.4.3 not compatible with base-4.14 (GHC 8.10)

### ISSUE THREAD

**Issue by ysangkok** [diagrams/diagrams-lib#350]
If this is fixed, might as well check for compatibility with the 9.0 release candidate also.

If you want, I can send a PR!

**Comment by bgamari** [comment]
Indeed it would be great to have a release compatible with 8.10.

**Comment by byorgey** [comment]
Fixed by #357 .  Should be a new release shortly.
