### ISSUE TITLE
Linear constraint-solving module for diagram layout

### ISSUE THREAD

**Issue by fryguybob** [diagrams/diagrams-lib#8]
(Imported from <http://code.google.com/p/diagrams/issues/detail?id=12>. Original issue from byor...@gmail.com on January 15, 2011, 01:25:26 AM UTC)

There should be a module in the standard library providing an interface for specifying relative positions of subdiagrams via linear constraints (= equations or possibly even inequalities?), which then solves the constraints and takes care of actually positioning the diagrams as necessary.

**Comment by byorgey** [comment]
I'm now working on this using `mfsolve` for the constraint solving.

**Comment by jeffreyrosenbluth** [comment]
Interesting, is there any similarity to Cassowary?
https://en.wikipedia.org/wiki/Cassowary_(software)

**Comment by byorgey** [comment]
I am not familiar with Cassowary, but yes, it seems similar.  Differences
that I can see: mfsolve deals with equalities only (no inequalities) and
there is no way to specify constraints as being required or
preferred---every constraint is required.  On the other hand, mfsolve is
able to work with non-linear constraints, whereas it seems Cassowary does
not.  In any case, I think my approach should scale easily if we switch to
a more powerful constraint-solving engine in the future.
